// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "Fulcrum"
    public static let version = "0.6.0"
    public static let build: Int64 = 6
    public static let identifier = "site.jrtx.fulcrum"
    public static let releaseChannel = "stable"
}

public enum RivetTypes {
    public struct UpdateCheck: Sendable {
        public let status: String
        public let error: String?
        public let current_version: String
        public let available_version: String?
        public let build: Int64?
        public let published_at: String?
        public let installer: String?
        public let size_bytes: Int64?
        public init(status: String, error: String?, current_version: String, available_version: String?, build: Int64?, published_at: String?, installer: String?, size_bytes: Int64?) {
            self.status = status
            self.error = error
            self.current_version = current_version
            self.available_version = available_version
            self.build = build
            self.published_at = published_at
            self.installer = installer
            self.size_bytes = size_bytes
        }
    }

    public struct UpdateState: Sendable {
        public let phase: String
        public let percent: Int64
        public let message: String?
        public let downloaded_path: String?
        public let available_version: String?
        public init(phase: String, percent: Int64, message: String?, downloaded_path: String?, available_version: String?) {
            self.phase = phase
            self.percent = percent
            self.message = message
            self.downloaded_path = downloaded_path
            self.available_version = available_version
        }
    }

}

private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode__List_String_(_ v: [String]) -> RivetValue { .list(v.map(encode_String)) }
private func encode__List_List_String_(_ v: [[String]]) -> RivetValue { .list(v.map(encode__List_String_)) }
private func encode_Void(_ v: Void) -> RivetValue { .null }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode__Optional_String_(_ v: String?) -> RivetValue { v.map(encode_String) ?? .null }
private func encode__Optional_Int64_(_ v: Int64?) -> RivetValue { v.map(encode_Int64) ?? .null }
private func encode_UpdateCheck(_ v: RivetTypes.UpdateCheck) -> RivetValue { .list([encode_String(v.status), encode__Optional_String_(v.error), encode_String(v.current_version), encode__Optional_String_(v.available_version), encode__Optional_Int64_(v.build), encode__Optional_String_(v.published_at), encode__Optional_String_(v.installer), encode__Optional_Int64_(v.size_bytes)]) }
private func encode_UpdateState(_ v: RivetTypes.UpdateState) -> RivetValue { .list([encode_String(v.phase), encode_Int64(v.percent), encode__Optional_String_(v.message), encode__Optional_String_(v.downloaded_path), encode__Optional_String_(v.available_version)]) }

private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode__List_String_(_ v: RivetValue) throws -> [String] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List String)") }; return try xs.map(decode_String) }
private func decode__List_List_String_(_ v: RivetValue) throws -> [[String]] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List (List String))") }; return try xs.map(decode__List_String_) }
private func decode_Void(_ v: RivetValue) throws -> Void { guard case .null = v else { throw RivetGeneratedError.typeMismatch("Void") } }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode__Optional_String_(_ v: RivetValue) throws -> String? { if case .null = v { return nil }; return try decode_String(v) }
private func decode__Optional_Int64_(_ v: RivetValue) throws -> Int64? { if case .null = v { return nil }; return try decode_Int64(v) }
private func decode_UpdateCheck(_ v: RivetValue) throws -> RivetTypes.UpdateCheck { guard case .list(let xs) = v, xs.count == 8 else { throw RivetGeneratedError.typeMismatch("UpdateCheck") }; return RivetTypes.UpdateCheck(status: try decode_String(xs[0]), error: try decode__Optional_String_(xs[1]), current_version: try decode_String(xs[2]), available_version: try decode__Optional_String_(xs[3]), build: try decode__Optional_Int64_(xs[4]), published_at: try decode__Optional_String_(xs[5]), installer: try decode__Optional_String_(xs[6]), size_bytes: try decode__Optional_Int64_(xs[7])) }
private func decode_UpdateState(_ v: RivetValue) throws -> RivetTypes.UpdateState { guard case .list(let xs) = v, xs.count == 5 else { throw RivetGeneratedError.typeMismatch("UpdateState") }; return RivetTypes.UpdateState(phase: try decode_String(xs[0]), percent: try decode_Int64(xs[1]), message: try decode__Optional_String_(xs[2]), downloaded_path: try decode__Optional_String_(xs[3]), available_version: try decode__Optional_String_(xs[4])) }

public enum RivetEvent: Sendable {
    case copy_to_clipboard(String)
    case notify(String)
    case open_url(String)
    case update_available(String)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "copy-to-clipboard": return .copy_to_clipboard(try decode_String(value))
        case "notify": return .notify(try decode_String(value))
        case "open-url": return .open_url(try decode_String(value))
        case "update-available": return .update_available(try decode_String(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func clipboard_clear() async throws -> Int64 {
        let result = try await client.call("clipboard-clear", arguments: [])
        return try decode_Int64(result)
    }
    public func clipboard_history(query: String) async throws -> [[String]] {
        let result = try await client.call("clipboard-history", arguments: [encode_String(query)])
        return try decode__List_List_String_(result)
    }
    public func clipboard_record(text: String) async throws -> String {
        let result = try await client.call("clipboard-record", arguments: [encode_String(text)])
        return try decode_String(result)
    }
    public func health() async throws -> String {
        let result = try await client.call("health", arguments: [])
        return try decode_String(result)
    }
    public func index_rebuild() async throws -> Int64 {
        let result = try await client.call("index-rebuild", arguments: [])
        return try decode_Int64(result)
    }
    public func plugins_list() async throws -> [[String]] {
        let result = try await client.call("plugins-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func plugins_reload() async throws -> Void {
        let result = try await client.call("plugins-reload", arguments: [])
        return try decode_Void(result)
    }
    public func row_actions(id: String, arg: String) async throws -> [[String]] {
        let result = try await client.call("row-actions", arguments: [encode_String(id), encode_String(arg)])
        return try decode__List_List_String_(result)
    }
    public func run_action(id: String, arg: String) async throws -> String {
        let result = try await client.call("run-action", arguments: [encode_String(id), encode_String(arg)])
        return try decode_String(result)
    }
    public func search(query: String) async throws -> [[String]] {
        let result = try await client.call("search", arguments: [encode_String(query)])
        return try decode__List_List_String_(result)
    }
    public func settings_list() async throws -> [[String]] {
        let result = try await client.call("settings-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func settings_set(key: String, value: String) async throws -> Bool {
        let result = try await client.call("settings-set", arguments: [encode_String(key), encode_String(value)])
        return try decode_Bool(result)
    }
    public func snippet_delete(id: String) async throws -> Bool {
        let result = try await client.call("snippet-delete", arguments: [encode_String(id)])
        return try decode_Bool(result)
    }
    public func snippet_list() async throws -> [[String]] {
        let result = try await client.call("snippet-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func snippet_save(id: String, name: String, keyword: String, text: String) async throws -> String {
        let result = try await client.call("snippet-save", arguments: [encode_String(id), encode_String(name), encode_String(keyword), encode_String(text)])
        return try decode_String(result)
    }
    public func update_check(manual: Bool) async throws -> RivetTypes.UpdateCheck {
        let result = try await client.call("update-check", arguments: [encode_Bool(manual)])
        return try decode_UpdateCheck(result)
    }
    public func update_download() async throws -> Void {
        let result = try await client.call("update-download", arguments: [])
        return try decode_Void(result)
    }
    public func update_state() async throws -> RivetTypes.UpdateState {
        let result = try await client.call("update-state", arguments: [])
        return try decode_UpdateState(result)
    }

    // Shared state
    public func get_hotkey() async throws -> String {
        let result = try await client.getState("hotkey")
        return try decode_String(result)
    }
    @discardableResult
    public func set_hotkey(_ value: String) async throws -> String {
        let result = try await client.setState("hotkey", value: encode_String(value))
        return try decode_String(result)
    }
    public func get_theme() async throws -> String {
        let result = try await client.getState("theme")
        return try decode_String(result)
    }
    @discardableResult
    public func set_theme(_ value: String) async throws -> String {
        let result = try await client.setState("theme", value: encode_String(value))
        return try decode_String(result)
    }
    public func get_version() async throws -> String {
        let result = try await client.getState("version")
        return try decode_String(result)
    }
    @discardableResult
    public func set_version(_ value: String) async throws -> String {
        let result = try await client.setState("version", value: encode_String(value))
        return try decode_String(result)
    }
}
