// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig { public static let moduleName = "backend"; public static let entryName = "start" }

private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode__List_String_(_ v: [String]) -> RivetValue { .list(v.map(encode_String)) }
private func encode__List_List_String_(_ v: [[String]]) -> RivetValue { .list(v.map(encode__List_String_)) }
private func encode_Void(_ v: Void) -> RivetValue { .null }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }

private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode__List_String_(_ v: RivetValue) throws -> [String] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List String)") }; return try xs.map(decode_String) }
private func decode__List_List_String_(_ v: RivetValue) throws -> [[String]] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List (List String))") }; return try xs.map(decode__List_String_) }
private func decode_Void(_ v: RivetValue) throws -> Void { guard case .null = v else { throw RivetGeneratedError.typeMismatch("Void") } }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }

public enum RivetEvent: Sendable {
    case copy_to_clipboard(String)
    case notify(String)
    case open_url(String)
    case update_available(String)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "copy-to-clipboard": return .copy_to_clipboard(try decode_String(value))
        case "notify": return .notify(try decode_String(value))
        case "open-url": return .open_url(try decode_String(value))
        case "update-available": return .update_available(try decode_String(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func clipboard_clear() async throws -> Int64 {
        let result = try await client.call("clipboard-clear", arguments: [])
        return try decode_Int64(result)
    }
    public func clipboard_history(query: String) async throws -> [[String]] {
        let result = try await client.call("clipboard-history", arguments: [encode_String(query)])
        return try decode__List_List_String_(result)
    }
    public func clipboard_record(text: String) async throws -> String {
        let result = try await client.call("clipboard-record", arguments: [encode_String(text)])
        return try decode_String(result)
    }
    public func health() async throws -> String {
        let result = try await client.call("health", arguments: [])
        return try decode_String(result)
    }
    public func index_rebuild() async throws -> Int64 {
        let result = try await client.call("index-rebuild", arguments: [])
        return try decode_Int64(result)
    }
    public func plugins_list() async throws -> [[String]] {
        let result = try await client.call("plugins-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func plugins_reload() async throws -> Void {
        let result = try await client.call("plugins-reload", arguments: [])
        return try decode_Void(result)
    }
    public func run_action(id: String, arg: String) async throws -> String {
        let result = try await client.call("run-action", arguments: [encode_String(id), encode_String(arg)])
        return try decode_String(result)
    }
    public func search(query: String) async throws -> [[String]] {
        let result = try await client.call("search", arguments: [encode_String(query)])
        return try decode__List_List_String_(result)
    }
    public func settings_list() async throws -> [[String]] {
        let result = try await client.call("settings-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func settings_set(key: String, value: String) async throws -> Bool {
        let result = try await client.call("settings-set", arguments: [encode_String(key), encode_String(value)])
        return try decode_Bool(result)
    }
    public func snippet_delete(id: String) async throws -> Bool {
        let result = try await client.call("snippet-delete", arguments: [encode_String(id)])
        return try decode_Bool(result)
    }
    public func snippet_list() async throws -> [[String]] {
        let result = try await client.call("snippet-list", arguments: [])
        return try decode__List_List_String_(result)
    }
    public func snippet_save(id: String, name: String, keyword: String, text: String) async throws -> String {
        let result = try await client.call("snippet-save", arguments: [encode_String(id), encode_String(name), encode_String(keyword), encode_String(text)])
        return try decode_String(result)
    }
    public func update_check() async throws -> String {
        let result = try await client.call("update-check", arguments: [])
        return try decode_String(result)
    }

    // Shared state
    public func getHotkey() async throws -> String {
        let result = try await client.getState("hotkey")
        return try decode_String(result)
    }
    @discardableResult
    public func setHotkey(_ value: String) async throws -> String {
        let result = try await client.setState("hotkey", value: encode_String(value))
        return try decode_String(result)
    }
    public func getTheme() async throws -> String {
        let result = try await client.getState("theme")
        return try decode_String(result)
    }
    @discardableResult
    public func setTheme(_ value: String) async throws -> String {
        let result = try await client.setState("theme", value: encode_String(value))
        return try decode_String(result)
    }
    public func getVersion() async throws -> String {
        let result = try await client.getState("version")
        return try decode_String(result)
    }
    @discardableResult
    public func setVersion(_ value: String) async throws -> String {
        let result = try await client.setState("version", value: encode_String(value))
        return try decode_String(result)
    }
}
