#!/usr/bin/env racket
#lang racket/base

;; Regenerates app/core/gallery-data.rkt from the gallery/ directory.
;;
;; The packaged backend is a compiled bundle with no source tree, so the
;; first-party plugin files travel inside the binary as a JSON blob of
;; {relative-path: content}. The generated module is checked in; CI
;; regenerates it and fails on drift, the same discipline as the i18n
;; single source.
;;
;;   racket scripts/gen-gallery.rkt            # write if changed
;;   racket scripts/gen-gallery.rkt --check    # fail if it would change

(require json
         racket/file
         racket/format
         racket/match
         racket/path
         racket/runtime-path
         racket/string)

;; Resolved relative to this file, wherever it runs from.
(define-runtime-path here ".")

(define repo-root (path->string (simplify-path (build-path here 'up))))

(define gallery-dir (build-path repo-root "gallery"))
(define output-path (build-path repo-root "app" "core" "gallery-data.rkt"))

(struct entry (id files) #:transparent)

;; Embed LF line endings regardless of the checkout's autocrlf setting —
;; otherwise Windows working trees regenerate a different blob and the
;; freshness check fails.
(define (read-file-lf path)
  (string-replace (file->string path) "\r\n" "\n"))

;; One file per plugin: the manifest and every non-hidden, non-build file.
(define (plugin-files dir)
  (for/list ([f (in-list (sort (directory-list dir) string<? #:key path->string))]
             #:when (let ([name (path->string f)])
                      (and (file-exists? (build-path dir f))
                           (not (string-prefix? name "."))
                           (not (string-suffix? name "~"))
                           (not (string-suffix? name ".pyc")))))
    (path->string f)))

(define (collect)
  (unless (directory-exists? gallery-dir)
    (error 'gen-gallery "gallery directory not found: ~a" gallery-dir))
  (for/list ([sub (in-list (sort (directory-list gallery-dir) string<? #:key path->string))]
             #:when (directory-exists? (build-path gallery-dir sub)))
    (define dir (build-path gallery-dir sub))
    (define manifest (with-handlers ([exn:fail? (lambda (_) #f)])
                       (hash-ref (string->jsexpr (file->string (build-path dir "manifest.json"))) 'id #f)))
    (unless manifest
      (error 'gen-gallery "gallery/~a has no valid manifest.json" sub))
    (entry manifest
           (for/hasheq ([f (in-list (plugin-files dir))])
             (values (string->symbol f)
                     (read-file-lf (build-path dir (string->path f))))))))

(define (render entries)
  (define blob
    (jsexpr->string
     (for/hasheq ([e (in-list entries)])
       (values (string->symbol (entry-id e)) (entry-files e)))))
  (string-append
   "#lang racket/base\n"
   "\n"
   ";; GENERATED by scripts/gen-gallery.rkt from gallery/ — do not edit.\n"
   ";; Regenerate with `racket scripts/gen-gallery.rkt` after changing any\n"
   ";; first-party plugin. CI regenerates and fails on drift.\n"
   "\n"
   "(provide gallery-blob)\n"
   "\n"
   ";; JSON object: {plugin-id: {relative-path: file-content}}\n"
   "(define gallery-blob\n"
   "  " (~s blob) ")\n"
   ))

(module+ main
  (define check? (equal? (current-command-line-arguments) #("--check")))
  (define entries (collect))
  (define blob (render entries))
  (define existing (with-handlers ([exn:fail? (lambda (_) #f)])
                     (file->string output-path)))
  (cond
    [(equal? blob existing)
     (printf "gallery-data.rkt is up to date\n")]
    [check?
     (raise-user-error 'gen-gallery
                       "app/core/gallery-data.rkt is stale; run racket scripts/gen-gallery.rkt")]
    [else
     (display-to-file blob output-path #:exists 'replace)
     (printf "wrote ~a (~a plugins)\n" output-path (length entries))]))
